use_frameworks!

platform :ios, '9.0'

target 'JSBridgeZ_Example' do
  pod 'JSBridgeZ', :path => '../'

  target 'JSBridgeZ_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
